log:
  level: WARN

providers:
  docker:
    exposedByDefault: false
    endpoint: tcp://dockerproxy:2375
    network: traefik

api: {}

entryPoints:
  web:
    address: :80
  websecure:
    address: :443
  wandererpb:
    address: :8090

certificatesResolvers:
  default:
    acme:
      email: your@email.tld
      storage: acme.json
      tlsChallenge: {}
